### ISSUE TITLE
Contao 3.2.x support

### ISSUE THREAD

**Issue by stefanschleich** [timgatzky/teaserimages#1]
Are you planning to update this extension for newer versions of Contao? It worked fine until Contao 3.2. was released. I think it broke because of the changes in the Contao file handling that came with the 3.2. release.

**Comment by timgatzky** [comment]
Use the dev branch.
It's up to date.

**Comment by stefanschleich** [comment]
Yay, thanks. Are you going to submit this version to the extension repo too?

**Comment by timgatzky** [comment]
I will. Sometimes soon.
