### ISSUE TITLE
Teaser Richt Text Editor Problem

### ISSUE THREAD

**Issue by Selinaks** [timgatzky/teaserimages#2]
Hello,

after installing your extension Rich Text Editor is not working in my teasers. Is it normal?
It looks like this as a plain code area:

![image](https://f.cloud.github.com/assets/6897900/2368018/504685c6-a790-11e3-99ec-72bd299128cf.png)

**Comment by fritzmg** [comment]
This is normal. The teaserimages extension deactivates the Rich Text Editor by default (for some reason). You need to re-enable it in the System Settings.

**Comment by Selinaks** [comment]
Awesome! Thank you, fritzmg! It solved the problem :)
