### ISSUE TITLE
TI unter Contao 3.2.12

### ISSUE THREAD

**Issue by zonky2** [timgatzky/teaserimages#3]
Hallo Tim,

ich habe Teaserimages mal unter 3.2.12 installiert und beim Artikelteaser ein Bild hinzugefügt.

Wenn man in der Datenbank das "singleSRC" auf "binary(16)" umstellt, funktioniert die Sache soweit prima... 

Leider wird in dem Teaser-Textfeld der TinyMCE "raus geworfen" - es gibt in der Firebug-Console keine Fehlermeldung, dass was am JS klemmt.

Hast Du eine Idee zum Fix??

Dank und Gruss

zonky

**Comment by timgatzky** [comment]
In den Systemeinstellungen > Teaserimages den Tiny aktivieren.
Das Feld muss auch nicht umgestellt werden. Die aktuelle Version ist 3.2 kompatibel und höher. Das Feld ist binary
