### ISSUE TITLE
Support für Contao 3.5.x ?

### ISSUE THREAD

**Issue by akroii** [timgatzky/teaserimages#6]
Wird die Erweiterung noch weiterentwickelt?

Ich halte sie für sehr nützlich...

**Comment by timgatzky** [comment]
Was genau sollte rein? Eine 3er Version gibt es ja.

**Comment by akroii** [comment]
Meine Frage bisher war nur ob die Erweiterung noch weiterentwickelt wird.
Konkret erhalte ich keine Ausgabe des Teaserbildes im Template ce_teaser. Auch wird der RTE nicht bei aktivierter Erweiterung im Backend dargestellt.

**Comment by timgatzky** [comment]
Ich habe den aktuellen MASTER gerade in 3.5 getestet und alles funzt.
Die Responsive Images könnte man noch hinzufügen, aber die Erweiterung selbst arbeitet wie gewohnt.
- Auch wird der RTE nicht bei aktivierter Erweiterung im Backend dargestellt.
  Dann hast du eine alte Version oder in den Systemeinstellungen den RTE für den Teaser noch deaktiviert.

**Comment by corticelli** [comment]
Ja, funktioniert - aber: die Reponsive Images könnte man noch hinzufügen :)

Im Ernst: wäre der Aufwand dafür hoch? Ich würde dafür sammeln gehen ...

**Comment by thepixture** [comment]
Gibt es einen Workaround für Contao 3.5, damit das Bild auch gespeichert bleibt?

**Comment by timgatzky** [comment]
Wieso workaround? Der Master branch arbeitet ganz normal in Contao 3.5.x
Lediglich die responsive Images könnte man als Feature hinzufügen.
