### ISSUE TITLE
Bild wird nicht gespeichert

### ISSUE THREAD

**Issue by RalfFischer** [timgatzky/teaserimages#7]
Wir nutzen Contao 3.5.6 und wählen ein Bild im Backend beim Artikel, Gruppe Artikelteaser aus.
Das Bild wird auch beim entsprechenden Feld in klein angezeigt, ist aber nach dem Speichern weg.

Die Tabelle `tl_article` haben wir geprüft - das Feld `singleSRC` bleibt leer.

Fehlermeldungen oder Logeinträge gibt es keine.

**Comment by timgatzky** [comment]
Ich kann keine Fehlfunktion unter 3.5.6 feststellen.

**Comment by amenk** [comment]
Wir konnten es so korrigieren:

   ALTER TABLE  `tl_article` CHANGE  `singleSRC`  `singleSRC` BINARY( 16 ) NOT NULL DEFAULT  ''

@timgatzky Das Feld war `VARCHAR(255)` bei uns - damit ging es nicht. Hast du eine Idee warum das `VARCHAR(255)` war?

**Comment by timgatzky** [comment]
Das ist nicht nötig, wenn ihr die aktuelle Version nutzt und Contaos DB korrekt geupdated habt. 
Siehe dca/tl_article.php

Alles andere ist ein Fallback für Versionen < 3.2

https://github.com/timgatzky/teaserimages/blob/master/system/modules/teaserimages/dca/tl_article.php

**Comment by RalfFischer** [comment]
Wir verwenden die Version 2.0.0.9005.

**Comment by timgatzky** [comment]
Github ist die aktuelle Version. Das ER wurde vielleicht schon 3 Jahre nicht angefasst.
Ist aber auch überall im Contao Forum zu lesen. Nutzt einfach die aktuelle hier ausm Git.

**Comment by amenk** [comment]
@timgatzky Wie installiert man das denn? Fehlt da auf github nicht eine `composer.json` ?

**Comment by timgatzky** [comment]
Einfach Ordner kopieren und fertig. Wie jede Contao Erw., die man manuell installiert

**Comment by amenk** [comment]
Das wollen wir ja vermeiden... Wegen updates und so...
