### ISSUE TITLE
Composer json

### ISSUE THREAD

**Issue by amenk** [timgatzky/teaserimages#8]
Please add a composer.json die easier installation and updates

**Comment by timgatzky** [comment]
Die Datei allein reicht nicht. Man müsste das noch bei packagist anmelden usw. usw.
Da die Erw. vorerst keine Updates braucht, wird es bis Contao 4 keine Versionen geben.

**Comment by amenk** [comment]
Korrekt. Packagist muss man auch noch machen. Aber was ist das "usw. usw." ?

**Comment by timgatzky** [comment]
In einer ruhigen Minute sehe ich das mal vor.

**Comment by amenk** [comment]
:+1: keine Angst, ist nicht so schwer. Nützlich ist es auch noch den entsprechenden Hook in GitHub zu definieren, damit bei neuen Pushs automatisch Packagist aktualisiert wird. Falls was unklar ist, kannst du mich jederzeit fragen.
